name: foodfornothing
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.10.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  image_picker: ^0.8.6
  location: ^4.4.0
  carousel_pro: ^1.0.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.15
  firebase_auth: ^3.3.18
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.15
  firebase_core: ^1.17.0
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4 
  flutter_zoom_drawer: ^3.0.4+1
  cool_alert: ^1.1.0
  animations: ^2.0.7
  syncfusion_flutter_charts: ^21.1.38
  mask_text_input_formatter: ^2.4.0
  path: ^1.8.2
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.14
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.4.0
  fluttericon: ^2.0.0
  animated_text_kit: ^4.2.2
  get: ^4.6.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  flutter_geocoder: ^0.2.2-nullsafety
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  get_storage: ^2.1.1
  page_indicator: ^0.4.1
  # flutter_local_notifications: ^8.2.0
  # firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.7.0
  flutter_chat_bubble: ^2.0.0


  flutter_stripe: ^2.5.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
